[versions]
agp = "8.3.1"
annotations = "23.0.0"
cameraViewVersion = "1.3.4"
cameraxVersion = "1.3.4"
gson = "2.13.2"
guava = "33.5.0-android"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.8.0"
constraintlayout = "2.2.1"
telpoNfcAidlVersion = "1.0-2"
firebaseInappmessaging = "21.0.2"
retrofit = "2.9.0"
barcode_scanning = "17.0.2"
cameraView = "1.5.1"
firebaseCrashlyticsBuildtools = "3.0.6"

[libraries]
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraxVersion" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraxVersion" }
camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "cameraViewVersion" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraxVersion" }
camera-view-v134 = { module = "androidx.camera:camera-view", version.ref = "cameraViewVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
telpo-nfc-service-api-telpo-nfc-aidl = { module = "com.payneteasy.telpo-nfc-service-api:telpo-nfc-aidl", version.ref = "telpoNfcAidlVersion" }
firebase-inappmessaging = { group = "com.google.firebase", name = "firebase-inappmessaging", version.ref = "firebaseInappmessaging" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "barcode_scanning" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

